paginate: 50
paginate_path: "/pg/:num/"
markdown: kramdown
exclude: [vendor, Gemfile, LICENSE, README.md]
permalink: /photo/:slug/
collections:
  themes:
    title: Themes
    output: true
defaults:
- scope:
    path: ''
    type: themes
  values:
    permalink: "/theme/:slug/"
    layout: theme
    size: small
    highlight: true